api:
  temp-client-id: mw2_server
  temp-client-secret: $2a$10$EXjNWSTyNEVgPCRamUyH6eAQyPHQZP3VfV/9F9b.LrNeD.pP2gt5G # BCrypt Password (10 Round)
  servers: # name = Name of the server | ip = IP of the server | port = Port of the server | hash = name_port -> sha256
    - name: oilrig
      ip: 127.0.0.1
      port: 28960
      hash: 40A40A3A099676C832C2E78688CE37E01FE0A4BF747FACEF2B75D7A58C668903
    - name: highrise
      ip: 127.0.0.1
      port: 28961
      hash: 3454E28910DB9E22BDCB89BB3C9AEAA11724828BC7171FAC5C35B4C6B0ED932B
  security:
      header-check:
        enabled: false
      public-access:
        enabled: false

server:
  http2:
    enabled: false
  port: '28600'

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      location: '${java.io.tmpdir}'

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: 'jdbc:mariadb://localhost:3306/localdb?useUnicode'
    username: root
    password: <HIDDEN FROM GH>
    tomcat:
      connection-properties: useUnicode
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: >-
          org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG

#'!spring':
#  jpa:
#    hibernate:
#      ddl-auto: create-drop